olipo186/Git-Auto-Deploy

- GitAutoDeploy.conf.json.example
- GitAutoDeploy.py
Hi.
I made it using branch name from config. If there is no branch in config or it's empty it uses 'master'
Use case: I need to auto deploy different branches of the same repository.
Regards, Sergei.
> Configure branch name in config file

- Dockerfile
- GitAutoDeploy.py
Supporting a docker container requires fetching the ssh keys of repositories,
so a new option --ssh-keyscan was added.  This option tries to create a
/root/.ssh/authorized_keys based on the configured repositories.
> Dockerfile support

- GitAutoDeploy.py
The current master caused an "existing index.lock file" error (forgot the exact message) when I tried to use it as a web-hook in GitLab. I was able to fix this by changing the deploy command a bit in commit 5c4d7a7. The new version is a bit more verbose, but follows the suggestions made at http://gitolite.com/deploy.html#fetch----reverse-the-flow.
Apart from that I recognized that the current master does not deploy any submodules, which might be part of the repo. Therefore I added the appropriate commands to the clone and deploy command lines in commit f40eaa8. The `git submodule ...` calls do nothing if all submodules are up-to-date or if no submodules exist.
> Fix for locked repo bug & submodule support 

- GitAutoDeploy.conf.json.example
- GitAutoDeploy.py
Sometimes it is useful if you have forked repo and so on..
Default value is 'origin'
Here is where to change it.
Example:
```
[{
"url": "https://github.com/olipo186/Git-Auto-Deploy.git",
"branch": "master",
"remote": "origin",
"path": "~/repositories/Git-Auto-Deploy",
"deploy": "echo deploying"
},
```
> add option: remote

- GitAutoDeploy.py
Even if the config file defines a specific branch for a repository, the initial clone operation ignores this. Even though this will be corrected by the first pull request, the target repository will be in a unexpected state until then.
This pull request fixes this by adding the branch defined in the config file to the clone command line.
> Clone with branch

- GitAutoDeploy.py
- docs/Configuration.md
I found myself needing to filter the build events using the build
status (GitLab sends web hook events on build status changes so you
get "running" events which aren't very useful in deploy context).
Instead of building a whole lot of variable, parsing all possible
options I or others may want in the future, I coded the changes so that
any element from the web hook data is simply available for filtering.
I put in some code so that the earlier functionality works too -
specifically the action filter option which isn't an attribute in
GitLab's web hook data.
> Changes to a more versatile filter mechanism.

- config.json.sample
Signed-off-by: Anton Glukhov <anton.a.glukhov@gmail.com>
I was confused about how to add repository which works with git over ssh proto. I saw issue [#86](https://github.com/olipo186/Git-Auto-Deploy/issues/86) with exactly the same misunderstanding as well. So, here is a little clarity for this case.
> Add gitlab example with git over ssh url

- docs/Configuration.md
- gitautodeploy/gitautodeploy.py
- gitautodeploy/lock.py
- gitautodeploy/wrappers/git.py
- requirements.txt
This introduces Windows compatibility and allows Git-Auto-Deploy to run on Windows.
Has been tested on Windows 2008 R2 with Python 2.7 and MINGW64 from Git for Windows using bash.exe. This setup is the default configuration when installing [Git for Windows](https://git-scm.com/download/win).
Does not work with Python 3.5, but that is not due to this PR.
Windows compatibility fixes:
- Windows does not use signals like *nix does, but the Python [signal](https://docs.python.org/2/library/signal.html) module emulates some of them for convenience. ["On Windows, signal() can only be called with SIGABRT, SIGFPE, SIGILL, SIGINT, SIGSEGV, or SIGTERM. A ValueError will be raised in any other case."](https://docs.python.org/3/library/signal.html#signal.signal) A check has been implemented to see if …
> Windows compatibility

- gitautodeploy/wrappers/git.py
Right now only direct submodules inside the repo are updated - any submodules inside these direct submodules are ignored. This PR adds support for recursive submodules, which means that submodules inside submodules are updated as well. This is done by using the `--recursive` option of git's `submodule update` command, so the code changes are very small.
Apart from that the new submodule handling also uses the `--init` option to initialize updated submodules on the fly, so the `git submodule init` call can be removed completely, which makes the code required to update submoduels even smaller than the code of the current version.
> Recursive submodules

- GitAutoDeploy.py
Before:
```console
$ python GitAutoDeploy.py --daemon-mode
[WARNING] GitAutoDeploy.py is deprecated. Please use 'python gitautodeploy--daemon-mode' instead.
```
Now:
```console
$ python GitAutoDeploy.py --daemon-mode
[WARNING] GitAutoDeploy.py is deprecated. Please use 'python gitautodeploy --daemon-mode' instead.
```
The command and the option were joined instead of space-separated. The `split()` was removing the leading space.
> Fix joined command and options

- gitautodeploy/cli/config.py
- gitautodeploy/gitautodeploy.py
- gitautodeploy/wrappers/git.py
Right now existing repositories are not updated, when Git-Auto-Deploy is started. This causes repos to be out of sync, if GAD crashed and new commits have been pushed to the origin repo during the off-time. Also the branch and remote-url of the repo won't be updated if they have been changed in the config. This PR fixes this by initializing all existing repos when GAD starts.
Apart from that this PR does some minimal refactoring by moving the `repo_config` checks into the config module and enhancing the `clone` method of the git wrapper.
> Update remote-url and branch when changed in config

- gitautodeploy/cli/config.py
It was so hard to realize why auto-deploy works again and again until I read Gitlab WebHook documantation tips: 
"Your endpoint should send its HTTP response as fast as possible." and find this config here. 
Gitlab WebHook documantation :
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/web_hooks/web_hooks.md
> Default value detailed-response should be False

- gitautodeploy/parsers/common.py
GitHub does not allow the same SSH key to be used for multiple
repositories on the same server belonging to the same user, see:
http://snipe.net/2013/04/multiple-github-deploy-keys-single-server
The fix there doesn't work because the "url" field is used both to
get the repo and to identify it when a push comes in.  Using a local
SSH name for the repo works for getting the repo but then the name in
the push doesn't match.
This patch adds a 'repo' option that that can be set to the name of
the repo as given in the push.  If 'repo' is not set the behaviour
is unchanged.
Example:
"url": "git@repo-a-shortname/somerepo.git"
"repo": "git@github.com/somerepo.git"
> Allow more than one GitHub repo from the same user (also possible fix for issue 141)

- platforms/debian/stdeb/git-auto-deploy.init
- platforms/debian/stdeb/git-auto-deploy.postinst
This patch makes the pidfile be in /var/run/git-auto-deploy instead of /var/run so there are no permission problems.
Regards,
Henk
> Fix pidfile handling in Debian packaging

- gitautodeploy/parsers/gitlab.py
As seen here, the `pipeline` webhook is using the `project` key.
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/web_hooks/web_hooks.md
Should fix #142.
> Correct url retrieval, fixes #142

- gitautodeploy/httpserver.py
If the connection is open, Gitlab keeps waiting, resulting in a timeout
> Need to close the connection after send_response

- docs/Configuration.md
- gitautodeploy/parsers/bitbucket.py
- test/samples/bitbucket-server-pr-created-filter.negative.test-case.json
- test/samples/bitbucket-server-pr-created-filter.positive.test-case.json
Bitbucket Server is using different payload in the web hooks. Unfortunately, the payload doesn't contain any information about repository URL but it returns repository `slug` and repository `fullName`. Those two values could be used in the `match-url` parameter. This PR adds support for both [Post-Receive WebHooks](https://confluence.atlassian.com/bitbucketserver/post-service-webhook-for-bitbucket-server-776640367.html) and [Post Webhooks for Bitbucket](https://marketplace.atlassian.com/plugins/nl.topicus.bitbucket.bitbucket-webhooks/server/overview).
> Added support for Bitbucket Server

- gitautodeploy/httpserver.py
I'm running GAD behind a reverse proxy which also handles SSL termination.
I've changed the `validate_web_ui_https` method to return `TRUE` when `config['web-ui-require-https']` is `false`. Now I can access the web ui behind my reverse proxy.
Cheers,
Chris
> standalone 'web-ui-require-https' check

- README.md
Github's has changed the name of the config section for webhooks on their web client, now it's called "Webhooks" instead of "Webhooks and services".
> Update the name of a UI button

- .github/workflows/create-docker-images.yml
- .github/workflows/docker-tag.sh
- Dockerfile
- docker/examples/gitautodeploy-base-usage/README.md
- docker/examples/gitautodeploy-base-usage/app/deploy-app.py
- docker/examples/gitautodeploy-base-usage/image/Dockerfile
- docker/examples/gitautodeploy-base-usage/image/my.config.json
- docker/image-gitautodeploy/Dockerfile
- docker/image-gitautodeploy/README.md
Hi @olipo186,
I've found that the Dockerfile isn't buildable anymore. It shows me following when I try to build:
Step 1/5 : FROM google/python-runtime
pull access denied for google/python-runtime, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
That's why I've fixed the Dockerfile by making it _alpine_ based. Also I've added a description and example. Looks like the PR relates to #93 and #42
Apart from that I add a GitHub Action that builds image and pushes it to Docker packages, so people don't need DockerHub anymore to use GAD as docker image. Package of this repo becomes source of truth.
Feel free to propose cuts of the PR if you don't want something of above to be merged. I'll split changes to several parts and push less to …
> Fix Dockerfile. Build and push image to Github packages. Add description and example.
